apiVersion: v1
kind: Secret
metadata:
  name: {{ include "instantai-api.fullname" . }}
  labels:
    {{- include "instantai-api.labels" . | nindent 4 }}
type: Opaque
data:
  application.yml: {{ include "instantai-api.applicationConfig" . | b64enc | quote }}
