apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "notebook-controller.fullname" . }}-role-binding
  labels:
    {{- include "notebook-controller.labels" . | nindent 4 }}
    kustomize.component: notebook-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "notebook-controller.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "notebook-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }} 