name: Publish Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'instantai/Chart.yaml'
      - 'instantai-api/Chart.yaml'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Set lowercase variables
        run: |
          echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "REPO_NAME_LC=$(basename $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish instantai chart
        if: contains(github.event.head_commit.modified, 'instantai/Chart.yaml')
        run: |
          helm package instantai
          helm push instantai-$(yq e '.version' instantai/Chart.yaml).tgz oci://ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.REPO_NAME_LC }}

      - name: Publish instantai-api chart
        if: contains(github.event.head_commit.modified, 'instantai-api/Chart.yaml')
        run: |
          helm package instantai-api
          helm push instantai-api-$(yq e '.version' instantai-api/Chart.yaml).tgz oci://ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.REPO_NAME_LC }} 